### ISSUE TITLE
Verify hash without building a tree with all hashes

### ISSUE THREAD

**Issue by Araton95** [miguelmota/merkletreejs#14]
For getting the Proof of some hash we need to build a Merkle tree with all leaves, but why we need to build a Merkle tree for verifying the hash, if we have a Proof.

Seems the Merkle tree solves the issue of using all hashes for verifying the one, but here we need to use all hashes for verifying, which is a not-optimized solution.

Maybe I miss something, will be glad for an answer.
Thanks in advance.

**Comment by add19** [comment]
For verifying we should just provide the nodes which actually form an audit trail towards the merkle root. We could generate this proof by recursion.
1. For the given leaf node(consider it as childnode) determine its parent
2. For the parent node determine if the childnode is left child or the right child, if it is left add the right child to the audit trail and vice versa.
3. Now consider the parent node as the new childnode and recursively call the function with this new parent node and the audit trail.
I might have misinterpreted the problem but if it is correct then i think this will lead to a right solution.

**Comment by hendrikttan** [comment]
Verify function doesn't utilise leaves used when creating MerkleTree obj. It should be ok to create a MerkleTree obj with empty array (instead of original leaves), and with the same hashAlgorithm and options (if any). Then provide the proofs, leaf, and root (no changes here) for verify().

**Comment by miguelmota** [comment]
Yes @hendrikttan is correct; you may instantiate merkle tree as usual but with empty leaves and then call verify:

```js
const tree = new MerkleTree([], hashFn, options)
const verified = tree.verify(proof, targetNode, root)
```

or use the static verify method:

```js
const verified = MerkleTree.verify(proof, targetNode, root, hashFn, options)
```
