### ISSUE TITLE
Compare with zk-snark & zk-stark ? 

### ISSUE THREAD

**Issue by maneeshgrover** [miguelmota/merkletreejs#15]
How would this be different from zk-snark or zk-stark ?

**Comment by martindale** [comment]
**zk-SNARKs** and **zk-STARKs** are cryptographic schemes for exchanging information, whereas a **Merkle Tree** is simply a data structure for _storing_ information.  They are generally unrelated concepts.

**Comment by maneeshgrover** [comment]
Thanks and i agree. But in current proof generation are we using snark or stark scheme ? We follow the same process of generating proof via snark/stark and how is it different ?

**Comment by miguelmota** [comment]
Merkle tree proofs prove that a leaf node is part of the tree, while zksnark proofs prove that an input fulfills a set of constraints without revealing the raw input. 

Will be closing since it's not an actual issue regarding this library and the question is suited better for stackoverflow.
