### ISSUE TITLE
Typescript doesn't compile

### ISSUE THREAD

**Issue by jbelelieu** [miguelmota/merkletreejs#18]
My project can't compile in typescript because of this line:

`const position = isRightNode ? 'left' : 'right'`

The issues is related to typescript's `noUnusedLocals` compiler option. You need to remove that line.

**Comment by jbelelieu** [comment]
Just as a followup to this, it looks like my pull request was merged, but the npm package wasn't updated, so the issue still exists when I install the npm package. Can you get that updated?

**Comment by miguelmota** [comment]
Thanks for being patient. It's now bumped on NPM.
