### ISSUE TITLE
The index.ts file should not be included in the published package

### ISSUE THREAD

**Issue by JaceHensley** [miguelmota/merkletreejs#22]
I don't think the index.ts file should be included in the published package. It causes issues if consumers of this library have `noImplicitAny: true` in their tsconfig.json.

Instead it should just be dist/. This can be done with the `files` field in package.json: `"files": ["dist"]`

Also since the repo is written in TS the `typings` folder isn't needed. I can a PR up to fix this if it would be accepted.

**Comment by miguelmota** [comment]
Thanks for the suggestions! they are implemented in the latest release.
