### ISSUE TITLE
Feature: Multiproofs

### ISSUE THREAD

**Issue by 3esmit** [miguelmota/merkletreejs#23]
Add capability for tree calculating the multiproofs for the merkletree. 

It should support multiple solutions:
- as in https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/merkle-proofs.md#merkle-multiproofs
- as in https://github.com/status-im/account-contracts/blob/develop/contracts/cryptography/MerkleMultiProof.sol

**Comment by miguelmota** [comment]
quick question @3esmit does your smart contract multiproof verifier work with multiproofs generated with vbuterin's [merkle lib](https://github.com/ethereum/research/blob/975fcd280390470fd256ce823dc2ed485a923a62/merkle_tree/merk.py)?

**Comment by 3esmit** [comment]
No, is a different approach. Instead of using the integers idx identifing the position to read next element, it uses a boolean that specify if the next value should be hashed against the provided proof array or the in memory result array, and the proof array must be provided in order of use. I didn't tested what is the most gas economic. Any method would work for me, however I would go for what is more cheap in EVM, however there might be a use-case where proofs must be given out of order (maybe for unbalanced trees?).

**Comment by miguelmota** [comment]
I see, so the leaves, layers, and proofs must all be sorted. I implemented the proof generating scheme you wrote, so this library is compatible with the solidity verifier as in the statusim account contract:

```js
const MerkleMultiProof = artifacts.require('MerkleMultiProof')
const { MerkleTree } = require('merkletreejs')
const keccak256 = require('keccak256')

const contract = await MerkleMultiProof.new()

const leaves = ['a', 'b', 'c', 'd', 'e', 'f'].map(keccak256).sort(Buffer.compare)
const tree = new MerkleTree(leaves, keccak256, { sort: true })

const root = tree.getRoot()
const proofLeaves = ['b', 'f', 'd'].map(keccak256).sort(Buffer.compare)
const proof = tree.getMultiProof(proofLeaves)
const proofFlags = tree.getProofFlags(proofLeaves, proof)

const verified = await contract.verifyMultiProof.call(root, proofLeaves, proof, proofFlags)
console.log(verified) // true
```

It also supports generating a proof by giving it a flat array representing the tree and the leave indices as in vbuterin's merk.py verfier:

```js
const crypto = require('crypto')
const { MerkleTree } = require('merkletreejs')
const sha256 = (data) => crypto.createHash('sha256').update(data).digest()

const leaves = Array(16).fill(0).map((x, i) => {
  const b = Buffer.alloc(32)
  b.writeUIntLE(i, 31, 1)
  return b
})

const tree = new MerkleTree(leaves, sha256)

const indices = [2, 5, 6]
const pLeaves = indices.map(i => leaves[i])

const fTree = tree.getLayersFlat()
const root = fTree[1]
const depth = Math.log2((fTree.length/2)|0)
const proof = tree.getMultiProof(fTree, indices)


const verified = tree.verifyMultiProof(root, indices, pLeaves, depth, proof)
console.log(verified) // true
```

Let me know if this satisfies the requirements you were thinking of and thanks for the multiproof examples!
