### ISSUE TITLE
Verify fails if there is only one leaf.

### ISSUE THREAD

**Issue by Alko89** [miguelmota/merkletreejs#25]
Sometimes when building a merkle tree from data, I might receive only one leaf hash to work with.
If this is the case verify function will return false. I have checked the code and figured out the issue is because of this line.

https://github.com/miguelmota/merkletreejs/blob/d78ea67599962911ae61271ec75fe7c7c155fc76/index.ts#L562

Because there is only one hash the proof length is 0, but the tree will still return a root (hash of that one leaf).
Is this intentional? Removing the line fixes my issue. How is the tree intended to work in cases when there is only one leaf node?

**Comment by miguelmota** [comment]
@Alko89 thanks for reporting the issue. I added a test case for this and should be fixed now in the latest version.

**Comment by Alko89** [comment]
Thanks for such a quick response and fix! :smiley: really appreciate it!
