### ISSUE TITLE
getHexLayers, getHexLeaves not methods

### ISSUE THREAD

**Issue by emsheets** [miguelmota/merkletreejs#26]
The documentation describes functions that are not present in the code.

**Comment by miguelmota** [comment]
The methods are in the [code](https://github.com/miguelmota/merkletreejs/blob/master/index.ts#L211) and the methods are used in the [tests](https://github.com/miguelmota/merkletreejs/blob/master/test/merkletree.test.js#L22). Do you have a code snippet to share in order to debug?

**Comment by miguelmota** [comment]
Closing ticket due to inactivity.
