### ISSUE TITLE
Constructing leaves from objects

### ISSUE THREAD

**Issue by alvin854** [miguelmota/merkletreejs#34]
I can `keccak` strings to construct the leaves of a Merkle tree, for example, `['a', 'b', 'c']`. But what's the recommended approach to constructing objects instead of merely `'a'`? Let's say:

    {
        address: "0x123",
        token: "0x456",
        amount: "15000000000000000000"
    }

In Solidity, to verify that the object exists in the tree, a leaf would be constructed via `bytes32 leaf = keccak256(abi.encodePacked(address, token, amount))` and that leaf would be verified along with the proof and root. How would you recommend constructing the above object as a leaf? 

Can a leaf be constructed simply with `web3.utils.soliditySha3(param1 [, param2, ...])`? So if...

    const hash0 = web3.utils.soliditySha3(address0, token0, amount0);
    const hash1 = web3.utils.soliditySha3(address1, token1, amount1);
    const leaves = [hash0, hash1]
    const tree = new MerkleTree(leaves, keccak)
    const proof = tree.getProof(hash0)

...would `leaves[0]` (`hash0`) in JS match `keccak256(abi.encodePacked(address0, token0, amount0))` in Solidity?

And is this the right approach to adding objects to a `MerkleTree`?

**Comment by miguelmota** [comment]
@alvin854 Yes that would perfectly work. The approach to serializing leaf objects is up to the developer but makes perfect sense to use abi encoder if you're dealing with solidity.

**Comment by miguelmota** [comment]
Related https://github.com/miguelmota/merkletreejs/issues/35
