### ISSUE TITLE
Arguments must be Buffers error when using ethereum/js-ethereum-cryptography (keccak256)

### ISSUE THREAD

**Issue by xpluscal** [miguelmota/merkletreejs#45]
When using ethereum/js-ethereum-cryptography and keccak256 for the trees, getHexProof fails with error "Arguments must be Buffers".

I saw a similar issue with Crypto-JS, but the solution outlined there didn't fix the issue.

Thanks in advance!

**Comment by miguelmota** [comment]
Hi, can you provide an simple example to reproduce? Thanks!

**Comment by miguelmota** [comment]
Should be fixed now in latest version

```js
const { MerkleTree } = require('merkletreejs')
const { keccak256 } = require('ethereum-cryptography/keccak')

const leaves = ['a', 'b', 'c'].map(v => keccak256(Buffer.from(v)))
const tree = new MerkleTree(leaves, keccak256)
console.log(tree.getHexRoot()) // 0xaff1208e69c9e8be9b584b07ebac4e48a1ee9d15ce3afe20b77a4d29e4175aa3
```

Thanks for reporting!

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/merkletreejs/commit/286c3966ebc1f9c58829c647dbb829a19da769dc
