### ISSUE TITLE
Using CryptoJS

### ISSUE THREAD

**Issue by Berkmann18** [miguelmota/merkletreejs#5]
I'm trying to test this library to see how I could use it with CryptoJS alongside other stuff and it seems to not like it even when I convert the hashes into buffers
```js
test('Simple', () => {
  const data = ['Lorem', 'Ipsum', 'Dolore', 'Sit', 'Amet'];
  const leaves = data.map(d => Buffer.from(SHA256(d).toString(), 'hex'));
  console.log(leaves);
  let tree = new MerkelTree(leaves, SHA256);
}
```
I get this error:
```cli
TypeError [ERR_INVALID_ARG_TYPE]: The "list[0]" argument must be one of type Array, Buffer, or Uint8Array. Received type object
    at Function.concat (buffer.js:479:13)
    at MerkleTree.createHashes (/home/maxie/Dropbox/Projects/SaCoin/node_modules/merkletreejs/index.js:57:23)
    at MerkleTree.createHashes (/home/maxie/Dropbox/Projects/SaCoin/node_modules/merkletreejs/index.js:86:10)
    at new MerkleTree (/home/maxie/Dropbox/Projects/SaCoin/node_modules/merkletreejs/index.js:37:10)
    at Object.<anonymous>.test (/home/maxie/Dropbox/Projects/SaCoin/tests/MerkelTree.test.js:9:14)
    at Object.asyncFn (/home/maxie/Dropbox/Projects/SaCoin/node_modules/jest-jasmine2/build/jasmine_async.js:108:37)
    at resolve (/home/maxie/Dropbox/Projects/SaCoin/node_modules/jest-jasmine2/build/queue_runner.js:56:12)
    at new Promise (<anonymous>)
    at mapper (/home/maxie/Dropbox/Projects/SaCoin/node_modules/jest-jasmine2/build/queue_runner.js:43:19)
    at promise.then (/home/maxie/Dropbox/Projects/SaCoin/node_modules/jest-jasmine2/build/queue_runner.js:87:41)
```
This error says that the leave inputs aren't buffers but they are (confirmed by `expect(leaves[0] instanceof Buffer).toBeTruthy();` passing) so I'm perplexed as to why that is happening?

I don't want to use crypto because all the crypto functions in my project are based on CryptoJS and work perfectly well.

**Comment by DonleeIO** [comment]
Thanks for highlighting this. I’ll look into it tomorrow.

**Comment by miguelmota** [comment]
Although the CryptoJS constructor type is called *Buffer*, CryptoJS buffers are not actually native Node.js buffers which is what's causing the error. 

```js
console.log(Buffer.isBuffer(SHA256('hello'))) // false
```

To get around this you can wrap the hashing function in order to return a `Buffer`.

```js
const AES = require('crypto-js/aes')
const SHA256 = require('crypto-js/sha256')
const MerkleTree = require('merkletreejs')

const bufferify = f => x => Buffer.from(f(x.toString()).toString(), 'hex')

const hashFn = bufferify(SHA256)
const leaves = ['a', 'b', 'c'].map(hashFn)
const tree = new MerkleTree(leaves, hashFn)

console.log(tree)

/ *
 MerkleTree {
  hashAlgo: [Function],
  leaves:
   [ <Buffer ca 97 81 12 ca 1b bd ca fa c2 31 b3 9a 23 dc 4d a7 86 ef f8 14 7c 4e 72 b9 ...
  ....
*/
```

We should however support CryptoJS in a future release

@Berkmann18 @DonleeIO

**Comment by miguelmota** [comment]
Latest release supports CryptoJS algos

**Comment by Berkmann18** [comment]
For some reason, the test works but whenever I use another hash for the leaves (e.g.: SHA3, SHA224, SHA256 from crypto-js the test fails until I change it to using sha3 from ethereumjs-util.

**Comment by miguelmota** [comment]
@Berkmann18 sha3 from ethereumjs-util is actually the keccak256 algo. The reason this is, is because ethereum implemented the sha3 algo when it wasn't finalized. The finalized version became sha3 and the ethereum version they implemented became keccak256 but they still kept the name sha3 even though it's an "older" version

using other algos for leaves in the test will fail because the digests will differ

**Comment by Berkmann18** [comment]
Ah okay, thanks for clearing that up.
