### ISSUE TITLE
Add documentation that input leaves should be strings?

### ISSUE THREAD

**Issue by 0xMako** [miguelmota/merkletreejs#50]
I had an issue using `merkletreejs` on the frontend, as Webpack (a common dependency in React) has a latest version that is incompatible with Buffer. 

It seems that this issue has been experienced by others. 
https://stackoverflow.com/questions/70530052/keccak-js-uncaught-refereanceerror-buffer-is-not-defined

**Comment by 0xMako** [comment]
Closed - I misunderstood the library documentation. The leaves should be an array of strings!

**Comment by jhernanx** [comment]
> I had an issue using `merkletreejs` on the frontend, as Webpack (a common dependency in React) has a latest version that is incompatible with Buffer.
> 
> It seems that this issue has been experienced by others. https://stackoverflow.com/questions/70530052/keccak-js-uncaught-refereanceerror-buffer-is-not-defined

There's a fix for this issue for those who stumble upon it later: https://stackoverflow.com/questions/68707553/uncaught-referenceerror-buffer-is-not-defined
