### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by Tias84** [miguelmota/merkletreejs#52]
Hi, I installed the library in a JS project and it works without problem, as soon as I imported the code I wrote in a project with React Typescript it doesn't work and gives me an error ```uncaught (in promise) ReferenceError: Buffer is not defined".

**Snippet Code**
![Code 2022-04-01 at 12 02](https://user-images.githubusercontent.com/63471942/161242121-07d40d7b-3c37-4f2e-a728-9e12f46ee52c.png)

**Error screenshot**
![Google Chrome 2022-04-01 at 12 00](https://user-images.githubusercontent.com/63471942/161241986-1a78c083-f9ad-4212-bdb7-678cd5fbfae1.png)

**Import**
![Code 2022-04-01 at 12 02](https://user-images.githubusercontent.com/63471942/161242246-79b78c3b-1fed-4e7b-b109-4896c5a26063.png)

**Comment by jhernanx** [comment]
Here you go, Webpack 5 issue, this fixed it for us and we were able to verify our Merkle tree on-chain in our smart contract 💪 

https://stackoverflow.com/questions/68707553/uncaught-referenceerror-buffer-is-not-defined
