### ISSUE TITLE
Efficient way to get proofs for all the leaves

### ISSUE THREAD

**Issue by charlesAuthentik** [miguelmota/merkletreejs#55]
Hi,

I'm curious if there's any efficient way to get all the proofs for all leaves?
I have a huge tree with tens of thousands of leaves, and I'd love to calculate all the proofs and store it.
Right now I'm looping the entire list and calculate the proof using getHexProof like this

```
 let claims = {};
 const leaves = merkleTree.getLeaves()
 for (let i = 0; i < leaves.length; i++) {
    let address = list[i].address;
    let leaf = leaves[i];
    let proof = merkleTree.getHexProof(leaf);
    claims[address] = {
      proof:  proof
 }
```
Is there a better way to do so? Really appreciate the help here!

**Comment by moorey777** [comment]
`exports.getHexProofs = (merkleTree) => {
  let layers = merkleTree.getLayers();
  let proof = [],
    proofs = [];

  dfs(layers, layers.length - 1, 0, proof, proofs);

  for (let i = 0; i < proofs.length; i++) {
    proofs[i] = proofs[i].map((item) => merkleTree.bufferToHex(item.data));
  }

  return proofs;
};

function dfs(layers, layerIndex, index, proof, proofs) {
  const isRightNode = index % 2;
  if (layerIndex == -1) {
    if (!isRightNode) proofs.push([...proof].reverse());
    return;
  }
  if(index >= layers[layerIndex].length) return;

  const layer = layers[layerIndex];
  const pairIndex = isRightNode ? index - 1 : index + 1;

  let pushed = false;
  if (pairIndex < layer.length) {
    pushed = true;
    proof.push({
      position: isRightNode ? 'left' : 'right',
      data: layer[pairIndex],
    });
  }

  let leftchildIndex = index * 2;
  let rightchildIndex = index * 2 + 1;

  dfs(layers, layerIndex - 1, leftchildIndex, proof, proofs);
  dfs(layers, layerIndex - 1, rightchildIndex, proof, proofs);

  if (pushed) proof.splice(proof.length - 1, 1);
}`

This should work

**Comment by moorey777** [comment]
```
exports.getHexProofs = (merkleTree) => {
  let layers = merkleTree.getLayers();
  let proof = [],
    proofs = [];

  dfs(layers, layers.length - 1, 0, proof, proofs);

  for (let i = 0; i < proofs.length; i++) {
    proofs[i] = proofs[i].map((item) => merkleTree.bufferToHex(item.data));
  }

  return proofs;
};

function dfs(layers, layerIndex, index, proof, proofs) {
  const isRightNode = index % 2;
  if (layerIndex == -1) {
    if (!isRightNode) proofs.push([...proof].reverse());
    return;
  }
  if(index >= layers[layerIndex].length) return;

  const layer = layers[layerIndex];
  const pairIndex = isRightNode ? index - 1 : index + 1;

  let pushed = false;
  if (pairIndex < layer.length) {
    pushed = true;
    proof.push({
      position: isRightNode ? 'left' : 'right',
      data: layer[pairIndex],
    });
  }

  let leftchildIndex = index * 2;
  let rightchildIndex = index * 2 + 1;

  dfs(layers, layerIndex - 1, leftchildIndex, proof, proofs);
  dfs(layers, layerIndex - 1, rightchildIndex, proof, proofs);

  if (pushed) proof.splice(proof.length - 1, 1);
}
```

This should work
